# TEST CODE
version: '3'
services:
  choisinsa-mysql:
    env_file:
      - mysql.env
    image: itchoi0429/choisinsa-mysql:latest
    volumes:
      - choisinsa-db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - choisinsa-app-network
networks:
  choisinsa-app-network:
    external:
      name: choisinsa-app-network
volumes:
  choisinsa-db-volume: {}

#  wordpress:
#    image: adoptopenjdk16
#    volumes:
#      - ./wp:/var/www/html
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_PASSWORD: wp