# TEST CODE
version: '3'
services:
  choisinsa-admin-app:
    ports:
      - 8081:8081
    image: itchoi0429/choisinsa-admin-app:latest
    container_name: choisinsa-admin-app
    build:
      context: .
      dockerfile: module-app-admin/Dockerfile
    depends_on:
      - choisinsa-mysql
    networks:
      - choisinsa-app-network

  choisinsa-client-app:
    ports:
      - 8080:8080
    image: itchoi0429/choisinsa-client-app:latest
    container_name: choisinsa-client-app
    build:
      context: .
      dockerfile: ./module-api-client/Dockerfile
    depends_on:
      - choisinsa-mysql
    networks:
      - choisinsa-app-network

  choisinsa-mysql:
    image: itchoi0429/choisinsa-mysql:latest
    container_name: choisinsa-mysql
#    container_name: choisinsa-mysql-1
    volumes:
      - choisinsa-db-volume:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - choisinsa-app-network

  choisinsa-redis:
    image: redis
    container_name: choisinsa-redis
    ports:
      - ${REDIS_CLIENT_PORT}:${REDIS_SERVER_PORT}
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    networks:
      - choisinsa-app-network

networks:
  choisinsa-app-network:
    external:
      name: choisinsa-app-network
volumes:
  choisinsa-db-volume: {}

#  wordpress:
#    image: adoptopenjdk16
#    volumes:
#      - ./wp:/var/www/html
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_PASSWORD: wp